import { SynonymRing } from "./SynonymRing"

const PRIME = 2_147_483_647
const PRIME_BIGINT = 2_147_483_647n
const DEFAULT_NUM_HASHES = 128
const U64_MASK = (1n << 64n) - 1n
const XXH64_PRIME_2 = 0xC2B2AE3D27D4EB4Fn
const XXH64_PRIME_3 = 0x165667B19E3779F9n
const SECRET_U32_0 = 0x396cfeb8
const SECRET_U32_4 = 0xbe4ba423
const SECRET_U64_56 = 0x4c263a81e69035e0n
const SECRET_U64_64 = 0xcb00c391bb52283cn

const te = new TextEncoder()

/**
 * Rust `NGramIndex::with_seed(None, None, 0)` coefficient projection.
 *
 * Rust reference: `../src/ngram.rs`
 * TS note: these constants are generated by Rust `StdRng::seed_from_u64(0)`,
 * matching the existing `aura-ts-verify-recall` deterministic verifier.
 */
const RUST_SEED_0_A = [
  1570054104, 1660993097, 55500930, 1254472462, 563007146, 1657829256, 469648040, 1704486668,
  1609192022, 2080777968, 2139575229, 299308606, 242375742, 2071968887, 106085810, 914188226,
  989087281, 1984838941, 487566073, 1201156958, 333695632, 1794221628, 439321804, 1080461908,
  1369556456, 1028321284, 1881361266, 1869728957, 135788565, 2119331355, 465569222, 2098206192,
  1970195574, 1454283400, 32265993, 148652318, 1327476884, 1318059337, 1686285104, 1429984776,
  181261422, 180312457, 1113925261, 1616921939, 1863531113, 188129986, 754028997, 402335502,
  1121936012, 2097397394, 566545182, 537202824, 2115194074, 1430252026, 1443252772, 1700352089,
  628272690, 1362513429, 73693663, 179506122, 415658669, 1408470540, 1248675325, 401071470,
  464360082, 684216305, 758223273, 1195696092, 1362552712, 38772150, 178633453, 695491336,
  527941358, 83291077, 1965801095, 948932991, 1310035530, 102247367, 1719923318, 1747585474,
  1806479243, 1966845994, 1644111408, 1889199186, 756125097, 1913025750, 1162108854, 229393688,
  616805958, 775645351, 1654407931, 1841684682, 373477766, 1107290900, 426960018, 230100300,
  605147304, 694634962, 604203569, 668769030, 1811808857, 1871484051, 1069901932, 1194905605,
  1662235101, 1119438872, 170169601, 2100682680, 1626399748, 456288784, 1548015779, 2118455955,
  370283806, 543979039, 740363607, 608968500, 1899731234, 1285775090, 431280321, 1152559020,
  1068540594, 275481312, 1767922972, 669212345, 1689656049, 1400821338, 1895790449, 1245537902
] as const

const RUST_SEED_0_B = [
  967566665, 462303317, 818044519, 1196991202, 1324885216, 539926408, 2102750964, 145419248,
  119332330, 1795677581, 246147715, 582957312, 62580139, 1402115187, 55929166, 63644365,
  855297028, 475700300, 725642818, 1880267832, 532991449, 1523007807, 303123913, 1418335713,
  1366535272, 1861795172, 2765125, 785424151, 1588746205, 84319434, 1421692928, 655476166,
  1222679694, 1139424320, 2041722388, 1400624149, 184795268, 1503688802, 1957458589, 1475103976,
  294064333, 1318359392, 1829905843, 1361601078, 1039442989, 1168300077, 1076896512, 187153141,
  917437373, 1050386904, 1218458555, 1317455096, 294403472, 94730591, 961945480, 216054150,
  1424484412, 186350430, 289718573, 1401867517, 1990727723, 736244154, 1264971403, 1245151770,
  111061298, 1496116219, 119268805, 3025301, 222888060, 1598153523, 314217164, 1982062213,
  1896698679, 344661645, 883118232, 1784618394, 380536412, 1551705406, 1434274940, 1170293514,
  2100328279, 1921458198, 1876075430, 936200038, 362705060, 409913597, 1931030784, 138863687,
  1718996604, 1485970223, 1785275845, 614263354, 1262283226, 213200947, 1099579703, 1031166111,
  657926864, 2083538104, 89530754, 1036923786, 593275977, 434266658, 909950413, 62999297,
  484306170, 453956598, 513823972, 1084877008, 406222279, 1430977244, 2072844610, 735096019,
  1031497065, 2092100201, 879098564, 884486099, 1159797515, 539262546, 859657146, 1282582784,
  1416719692, 2066451675, 805116310, 331581256, 718688739, 386807013, 1006643801, 1190611323
] as const

function xxh64Avalanche(input: bigint): bigint {
  let value = input & U64_MASK
  value ^= value >> 33n
  value = (value * XXH64_PRIME_2) & U64_MASK
  value ^= value >> 29n
  value = (value * XXH64_PRIME_3) & U64_MASK
  value ^= value >> 32n
  return value & U64_MASK
}

/**
 * Rust `xxh3_64` projection for the only byte lengths used by NGram tokenization.
 *
 * Rust reference: `xxhash_rust::xxh3::xxh3_64` through `NGramIndex::hash_str`.
 * NGram hashes either 1-2 byte short strings or 3-byte shingles.
 */
export function xxh3NGramHash(bytes: Uint8Array): number {
  if (bytes.byteLength > 3) {
    throw new RangeError("xxh3NGramHash only supports NGram short inputs up to 3 bytes")
  }
  if (bytes.byteLength === 0) {
    return Number(xxh64Avalanche(SECRET_U64_56 ^ SECRET_U64_64) & 0x7fffffffn)
  }

  const len = bytes.byteLength
  const c1 = bytes[0]!
  const c2 = bytes[len >> 1]!
  const c3 = bytes[len - 1]!
  const combo = (((c1 << 16) >>> 0) | ((c2 << 24) >>> 0) | c3 | (len << 8)) >>> 0
  const flip = BigInt((SECRET_U32_0 ^ SECRET_U32_4) >>> 0)
  return Number(xxh64Avalanche(BigInt(combo) ^ flip) & 0x7fffffffn)
}

function isRustAlphanumeric(char: string): boolean {
  return /^[\p{Alphabetic}\p{Number}]$/u.test(char)
}

/** Tokenize text into character trigram hashes. */
export function tokenizeNGram(text: string): ReadonlyArray<number> {
  const normalized = Array.from(text.toLowerCase(), (char) =>
    isRustAlphanumeric(char) ? char : " "
  ).join("")
  const clean = normalized.split(/\s+/u).filter((part) => part.length > 0).join(" ")
  if (clean.length === 0) return []

  const bytes = te.encode(clean)
  if (bytes.byteLength < 3) return [xxh3NGramHash(bytes)]

  const shingles: number[] = []
  for (let i = 0; i <= bytes.byteLength - 3; i++) {
    shingles.push(xxh3NGramHash(bytes.subarray(i, i + 3)))
  }
  shingles.sort((a, b) => a - b)

  let write = 0
  for (const shingle of shingles) {
    if (write === 0 || shingles[write - 1] !== shingle) {
      shingles[write] = shingle
      write += 1
    }
  }
  shingles.length = write
  return shingles
}

function randomCoefficientA(): number {
  return 1 + Math.floor(Math.random() * (PRIME - 1))
}

function randomCoefficientB(): number {
  return Math.floor(Math.random() * PRIME)
}

/**
 * MinHash-based n-gram index for approximate Jaccard similarity.
 *
 * 基于 MinHash 的 n-gram 索引，用于近似 Jaccard 相似度。
 *
 * Rust reference: `NGramIndex` in `../src/ngram.rs`.
 */
export class NGramIndex {
  private readonly aBig: ReadonlyArray<bigint>
  private readonly bBig: ReadonlyArray<bigint>
  private readonly signatures = new Map<string, ReadonlyArray<number>>()
  private readonly buckets: Array<Map<number, string[]>>

  private constructor(
    private readonly a: ReadonlyArray<number>,
    private readonly b: ReadonlyArray<number>,
    private readonly synonymRing?: SynonymRing
  ) {
    if (a.length !== b.length || a.length === 0) {
      throw new RangeError("NGramIndex requires non-empty equal coefficient arrays")
    }
    this.aBig = a.map(BigInt)
    this.bBig = b.map(BigInt)
    this.buckets = Array.from({ length: a.length }, () => new Map<number, string[]>())
  }

  /**
   * Create a new n-gram index.
   * 创建新的 n-gram 索引。
   *
   * NON-PARITY IMPLEMENTATION: this mirrors Rust's non-deterministic constructor shape,
   * but JS Math.random is not Rust thread_rng. Use `withSeed0` for verifier parity.
   */
  static random(numHashes = DEFAULT_NUM_HASHES, synonymRing?: SynonymRing): NGramIndex {
    const a = Array.from({ length: numHashes }, randomCoefficientA)
    const b = Array.from({ length: numHashes }, randomCoefficientB)
    return new NGramIndex(a, b, synonymRing)
  }

  /**
   * Create the deterministic verifier index equivalent to Rust `with_seed(None, None, 0)`.
   * 创建与 Rust verifier 等价的确定性索引。
   */
  static withSeed0(synonymRing?: SynonymRing): NGramIndex {
    return new NGramIndex(RUST_SEED_0_A, RUST_SEED_0_B, synonymRing)
  }

  /**
   * Expand text using synonym ring.
   * 使用 synonym ring 扩展文本。
   * Rust reference: `NGramIndex::expand` (`../src/ngram.rs`).
   */
  private expand(text: string): string {
    return this.synonymRing?.expand(text) ?? text
  }

  /**
   * Compute MinHash signature for a set of shingles.
   * 为 shingle 集合计算 MinHash 签名。
   */
  private minhash(shingles: ReadonlyArray<number>): ReadonlyArray<number> {
    const sig = Array<number>(this.a.length).fill(Number.MAX_SAFE_INTEGER)
    for (const s of shingles) {
      const sBig = BigInt(s)
      for (let i = 0; i < sig.length; i++) {
        const h = Number(((this.aBig[i]! * sBig) + this.bBig[i]!) % PRIME_BIGINT)
        if (h < sig[i]!) sig[i] = h
      }
    }
    return sig
  }

  /**
   * Index a record.
   * 为记录建立索引。
   */
  add(recordId: string, text: string): void {
    const shingles = tokenizeNGram(this.expand(text))
    if (shingles.length === 0) return

    const sig = this.minhash(shingles)

    // Populate LSH buckets.
    for (let i = 0; i < sig.length; i++) {
      const val = sig[i]!
      const bucket = this.buckets[i]!.get(val) ?? []
      bucket.push(recordId)
      this.buckets[i]!.set(val, bucket)
    }

    this.signatures.set(recordId, sig)
  }

  /**
   * Remove a record from the index.
   * 从索引中移除记录。
   */
  remove(recordId: string): void {
    const sig = this.signatures.get(recordId)
    if (!sig) return
    this.signatures.delete(recordId)

    for (let i = 0; i < sig.length; i++) {
      const bucket = this.buckets[i]!.get(sig[i]!)
      if (!bucket) continue
      const retained = bucket.filter((id) => id !== recordId)
      if (retained.length === 0) {
        this.buckets[i]!.delete(sig[i]!)
      } else {
        this.buckets[i]!.set(sig[i]!, retained)
      }
    }
  }

  /**
   * Query for similar records using LSH.
   *
   * Returns `[(similarity, record_id), ...]` sorted descending.
   * 使用 LSH 查询相似记录；返回按相似度降序排列的 `[(similarity, record_id), ...]`。
   */
  query(text: string, topK: number): Array<[number, string]> {
    if (topK <= 0) return []
    const shingles = tokenizeNGram(this.expand(text))
    if (shingles.length === 0) return []

    const querySig = this.minhash(shingles)
    const candidates = new Map<string, number>()
    for (let i = 0; i < querySig.length; i++) {
      const bucket = this.buckets[i]!.get(querySig[i]!)
      if (!bucket) continue
      for (const rid of bucket) {
        candidates.set(rid, (candidates.get(rid) ?? 0) + 1)
      }
    }

    const results: Array<[number, string]> = []
    for (const [rid, count] of candidates) {
      const similarity = count / this.a.length
      if (similarity > 0) results.push([similarity, rid])
    }
    results.sort((left, right) => right[0] - left[0])
    results.length = Math.min(results.length, topK)
    return results
  }

  /** Compute exact Jaccard similarity between two record signatures. 计算两个记录签名之间的 Jaccard 估计值。 */
  jaccard(idA: string, idB: string): number {
    const sigA = this.signatures.get(idA)
    const sigB = this.signatures.get(idB)
    if (!sigA || !sigB) return 0

    let matching = 0
    for (let i = 0; i < sigA.length; i++) {
      if (sigA[i] === sigB[i]) matching += 1
    }
    return matching / this.a.length
  }

  /** Find all pairs with Jaccard similarity >= threshold. 查找相似度不低于阈值的记录对。 */
  findSimilarPairs(threshold: number): Array<[string, string, number]> {
    const ids = Array.from(this.signatures.keys())
    const pairs: Array<[string, string, number]> = []
    for (let i = 0; i < ids.length; i++) {
      for (let j = i + 1; j < ids.length; j++) {
        const sim = this.jaccard(ids[i]!, ids[j]!)
        if (sim >= threshold) pairs.push([ids[i]!, ids[j]!, sim])
      }
    }
    return pairs
  }

  /** Number of indexed records. 已索引记录数量。 */
  len(): number {
    return this.signatures.size
  }

  isEmpty(): boolean {
    return this.signatures.size === 0
  }

  /** Check if a record is indexed. 检查记录是否已索引。 */
  contains(recordId: string): boolean {
    return this.signatures.has(recordId)
  }
}
