import { it } from "vitest"
import { assert } from "@effect/vitest"
import { SDRInterpreter } from "@aura/recall"

/**
 * Generated by Rust `aura-ts-recall-fixtures` from
 * `SDRInterpreter::text_to_sdr("alpha", false)`.
 */
const RUST_ALPHA_SDR: number[] = [
  277, 1670, 3391, 5819, 6402, 7265, 10276, 11944, 13390, 15818, 16401, 17264,
  20275, 21943, 23389, 25817, 26400, 27263, 30274, 31735, 31942, 33068, 33388,
  34405, 35816, 36129, 36399, 37262, 37466, 40273, 41941, 43387, 45076, 45815,
  46398, 46413, 47261, 50272, 51940, 53386, 55814, 56397, 57260, 57581, 58928,
  60271, 61939, 62802, 63385, 64900,
]

it("SDRInterpreter.textToSdr is deterministic and sorted", async () => {
  const sdr = await SDRInterpreter.default()
  const a = sdr.textToSdr("Hello 123", false)
  const b = sdr.textToSdr("Hello 123", false)
  assert.deepStrictEqual(a, b)
  assert.isTrue(a.every((v, i) => i === 0 || a[i - 1]! <= v))
})

it("SDRInterpreter.textToSdr matches the saved Rust fixture", async () => {
  const sdr = await SDRInterpreter.default()
  assert.deepStrictEqual(sdr.textToSdr("alpha", false), RUST_ALPHA_SDR)
})

it("SDRInterpreter.tanimotoSparse behaves sanely", async () => {
  const sdr = await SDRInterpreter.default()
  const a = sdr.textToSdr("Apple", false)
  const b = sdr.textToSdr("Apple Pie", false)
  const c = sdr.textToSdr("Banana", false)

  assert.strictEqual(sdr.tanimotoSparse(a, a), 1)
  assert.strictEqual(sdr.tanimotoSparse([], a), 0)
  assert.isTrue(sdr.tanimotoSparse(a, b) > sdr.tanimotoSparse(a, c))
})

it("SDRInterpreter.textToSdr is deterministic for non-ascii", async () => {
  const sdr = await SDRInterpreter.default()
  const a = sdr.textToSdr("你好，世界 123", false)
  const b = sdr.textToSdr("你好，世界 123", false)
  assert.deepStrictEqual(a, b)
})
